columns:
  jrf: [1, 2, 3]
  angle_0:
    angle_left: [7, 8, 9, 10, 15]
    angle_right: [18, 19, 20, 21, 26]
  angle_1:
    angle_left: [7, 8, 9, 10]
    angle_right: [18, 19, 20, 21]
  angle_2:
    angle_left: [7, 8, 10, 15]
    angle_right: [18, 19, 21, 26]
  angle_3:
    angle_left: [7, 9, 10, 15]
    angle_right: [18, 20, 21, 26]
  
random_seed: 3407
batch_size: 256
learning_rate: 0.001
epoch: 2000
save_folder_path: '/fashuxu/bingkui/ckpt/angle_{}/{}/{}/'

bestmodel:
  angle_0:
    lstm_2: '/fashuxu/bingkui/ckpt/angle_0/LSTM/LSTM_2_2024-06-27-02-27/best_model.pth'
    lstm_4: '/fashuxu/bingkui/ckpt/angle_0/LSTM/LSTM_4_2024-06-27-02-32/best_model.pth'
    lstm_6: '/fashuxu/bingkui/ckpt/angle_0/LSTM/LSTM_6_2024-06-25-09-13/best_model.pth'
    lstm_12: '/fashuxu/bingkui/ckpt/angle_0/LSTM/LSTM_12_2024-06-25-09-20/best_model.pth'
    lstm_18: '/fashuxu/bingkui/ckpt/angle_0/LSTM/LSTM_18_2024-06-25-09-32/best_model.pth'
    transformer_2: '/fashuxu/bingkui/ckpt/angle_0/Transformer/Transformer_2_2024-06-26-11-58/best_model.pth'
    transformer_4: '/fashuxu/bingkui/ckpt/angle_0/Transformer/Transformer_4_2024-06-26-12-16/best_model.pth'
    transformer_6: '/fashuxu/bingkui/ckpt/angle_0/Transformer/Transformer_6_2024-06-25-09-50/best_model.pth'
  angle_1:
    lstm_2: '/fashuxu/bingkui/ckpt/angle_1/LSTM/LSTM_2_2024-06-27-02-38/best_model.pth'
    lstm_4: '/fashuxu/bingkui/ckpt/angle_1/LSTM/LSTM_4_2024-06-27-02-41/best_model.pth'
    lstm_6: '/fashuxu/bingkui/ckpt/angle_1/LSTM/LSTM_6_2024-06-25-15-04/best_model.pth'
    lstm_12: '/fashuxu/bingkui/ckpt/angle_1/LSTM/LSTM_12_2024-06-25-15-10/best_model.pth'
    lstm_18: '/fashuxu/bingkui/ckpt/angle_1/LSTM/LSTM_18_2024-06-25-15-22/best_model.pth'
    transformer_2: '/fashuxu/bingkui/ckpt/angle_1/Transformer/Transformer_2_2024-06-26-12-52/best_model.pth'
    transformer_4: '/fashuxu/bingkui/ckpt/angle_1/Transformer/Transformer_4_2024-06-26-13-11/best_model.pth'
    transformer_6: '/fashuxu/bingkui/ckpt/angle_1/Transformer/Transformer_6_2024-06-25-15-40/best_model.pth'
  angle_2:
    lstm_2: '/fashuxu/bingkui/ckpt/angle_2/LSTM/LSTM_2_2024-06-27-02-49/best_model.pth'
    lstm_4: '/fashuxu/bingkui/ckpt/angle_2/LSTM/LSTM_4_2024-06-27-02-52/best_model.pth'
    lstm_6: '/fashuxu/bingkui/ckpt/angle_2/LSTM/LSTM_6_2024-06-25-20-56/best_model.pth'
    lstm_12: '/fashuxu/bingkui/ckpt/angle_2/LSTM/LSTM_12_2024-06-25-21-02/best_model.pth'
    lstm_18: '/fashuxu/bingkui/ckpt/angle_2/LSTM/LSTM_18_2024-06-25-21-14/best_model.pth'
    transformer_2: '/fashuxu/bingkui/ckpt/angle_2/Transformer/Transformer_2_2024-06-26-13-46/best_model.pth'
    transformer_4: '/fashuxu/bingkui/ckpt/angle_2/Transformer/Transformer_4_2024-06-26-14-05/best_model.pth'
    transformer_6: '/fashuxu/bingkui/ckpt/angle_2/Transformer/Transformer_6_2024-06-25-21-32/best_model.pth'
  angle_3:
    lstm_2: '/fashuxu/bingkui/ckpt/angle_3/LSTM/LSTM_2_2024-06-27-02-57/best_model.pth'
    lstm_4: '/fashuxu/bingkui/ckpt/angle_3/LSTM/LSTM_4_2024-06-27-03-00/best_model.pth'
    lstm_6: '/fashuxu/bingkui/ckpt/angle_3/LSTM/LSTM_6_2024-06-26-02-47/best_model.pth'
    lstm_12: '/fashuxu/bingkui/ckpt/angle_3/LSTM/LSTM_12_2024-06-26-02-54/best_model.pth'
    lstm_18: '/fashuxu/bingkui/ckpt/angle_3/LSTM/LSTM_18_2024-06-26-03-06/best_model.pth'
    transformer_2: '/fashuxu/bingkui/ckpt/angle_3/Transformer/Transformer_2_2024-06-26-14-41/best_model.pth'
    transformer_4: '/fashuxu/bingkui/ckpt/angle_3/Transformer/Transformer_4_2024-06-26-14-59/best_model.pth'
    transformer_6: '/fashuxu/bingkui/ckpt/angle_3/Transformer/Transformer_6_2024-06-26-03-23/best_model.pth'