columns:
  jrf: [1, 2, 3]
  angle_0:
    angle_left: [7, 8, 9, 10, 15]
    angle_right: [18, 19, 20, 21, 26]
  angle_1:
    angle_left: [7, 8, 9, 10]
    angle_right: [18, 19, 20, 21]
  angle_2:
    angle_left: [7, 8, 10, 15]
    angle_right: [18, 19, 21, 26]
  angle_3:
    angle_left: [7, 9, 10, 15]
    angle_right: [18, 20, 21, 26]
  
random_seed: 3407
batch_size: 256
learning_rate: 0.001
epoch: 2000
save_folder_path: '/fashuxu/bingkui/ckpt/angle_{}/{}/{}/'

bestmodel:
  angle_0:
    resnet18: '/fashuxu/IMR-MCF-All/ckpt_0/ResNet/resnet18_2024-04-01-15-04/best_model.pth'
    resnet34: '/fashuxu/IMR-MCF-All/ckpt_0/ResNet/resnet34_2024-04-01-20-13/best_model.pth'
    resnet50: '/fashuxu/IMR-MCF-All/ckpt_0/ResNet/resnet50_2024-04-01-20-12/best_model.pth'
    resnet101: '/fashuxu/IMR-MCF-All/ckpt_0/ResNet/resnet101_2024-04-01-20-14/best_model.pth'
    resnet152: '/fashuxu/IMR-MCF-All/ckpt_0/ResNet/resnet152_2024-04-10-22-13/best_model.pth'
    mlp: '/fashuxu/IMR-MCF-All/ckpt_0/MLP/mlp_2024-06-13-14-44/best_model.pth'
    lstm_5: '/fashuxu/IMR-MCF-All/ckpt_0/LSTM/5_2024-04-11-12-27/best_model.pth'
    lstm_10: '/fashuxu/IMR-MCF-All/ckpt_0/LSTM/10_2024-04-11-22-40/best_model.pth'
    lstm_15: '/fashuxu/IMR-MCF-All/ckpt_0/LSTM/15_2024-04-11-12-27/best_model.pth'
    lstm_20: '/fashuxu/IMR-MCF-All/ckpt_0/LSTM/20_2024-04-11-12-28/best_model.pth'
    transformer_6: '/fashuxu/IMR-MCF-All/ckpt_0/Transformer/transformer_6_2024-04-11-13-11/best_model.pth'
    transformer_12: '/fashuxu/IMR-MCF-All/ckpt_0/Transformer/transformer_12_2024-04-15-10-30/best_model.pth'
    transformer_18: '/fashuxu/IMR-MCF-All/ckpt_0/Transformer/transformer_18_2024-04-15-10-30/best_model.pth'
  angle_1:
    resnet18: '/fashuxu/IMR-MCF-All/ckpt_1/ResNet/resnet18_2024-04-25-23-44/best_model.pth'
    resnet34: '/fashuxu/IMR-MCF-All/ckpt_1/ResNet/resnet34_2024-04-25-23-44/best_model.pth'
    resnet50: '/fashuxu/IMR-MCF-All/ckpt_1/ResNet/resnet50_2024-04-25-23-44/best_model.pth'
    resnet101: '/fashuxu/IMR-MCF-All/ckpt_1/ResNet/resnet101_2024-04-25-23-44/best_model.pth'
    resnet152: '/fashuxu/IMR-MCF-All/ckpt_1/ResNet/resnet152_2024-04-25-23-45/best_model.pth'
    mlp: '/fashuxu/IMR-MCF-All/ckpt_1/MLP/mlp_2024-06-13-14-45/best_model.pth' 
    lstm_5: '/fashuxu/IMR-MCF-All/ckpt_1/LSTM/5_2024-04-12-23-28/best_model.pth'
    lstm_10: '/fashuxu/IMR-MCF-All/ckpt_1/LSTM/10_2024-04-12-23-29/best_model.pth'
    lstm_15: '/fashuxu/IMR-MCF-All/ckpt_1/LSTM/15_2024-04-12-23-29/best_model.pth'
    lstm_20: '/fashuxu/IMR-MCF-All/ckpt_1/LSTM/20_2024-04-12-23-29/best_model.pth'
    transformer_6: '/fashuxu/IMR-MCF-All/ckpt_1/Transformer/transformer_6_2024-04-12-23-30/best_model.pth'
    transformer_12: '/fashuxu/IMR-MCF-All/ckpt_1/Transformer/transformer_12_2024-04-12-23-31/best_model.pth'
    transformer_18: '/fashuxu/IMR-MCF-All/ckpt_1/Transformer/transformer_18_2024-04-12-23-31/best_model.pth'
  angle_2:
    resnet18: '/fashuxu/IMR-MCF-All/ckpt_2/ResNet/resnet18_2024-05-08-11-10/best_model.pth'
    resnet34: '/fashuxu/IMR-MCF-All/ckpt_2/ResNet/resnet34_2024-05-08-11-11/best_model.pth'
    resnet50: '/fashuxu/IMR-MCF-All/ckpt_2/ResNet/resnet50_2024-05-08-11-12/best_model.pth'
    resnet101: '/fashuxu/IMR-MCF-All/ckpt_2/ResNet/resnet101_2024-05-08-11-12/best_model.pth'
    resnet152: '/fashuxu/IMR-MCF-All/ckpt_2/ResNet/resnet152_2024-05-08-11-15/best_model.pth'
    mlp: '/fashuxu/IMR-MCF-All/ckpt_2/MLP/mlp_2024-06-13-14-45/best_model.pth'
    lstm_5: '/fashuxu/IMR-MCF-All/ckpt_2/LSTM/5_2024-04-13-17-13/best_model.pth'
    lstm_10: '/fashuxu/IMR-MCF-All/ckpt_2/LSTM/10_2024-04-13-17-13/best_model.pth'
    lstm_15: '/fashuxu/IMR-MCF-All/ckpt_2/LSTM/15_2024-04-13-17-13/best_model.pth'
    lstm_20: '/fashuxu/IMR-MCF-All/ckpt_2/LSTM/20_2024-04-13-17-13/best_model.pth'
    transformer_6: '/fashuxu/IMR-MCF-All/ckpt_2/Transformer/transformer_6_2024-04-13-17-14/best_model.pth'
    transformer_12: '/fashuxu/IMR-MCF-All/ckpt_2/Transformer/transformer_12_2024-04-13-17-15/best_model.pth'
    transformer_18: '/fashuxu/IMR-MCF-All/ckpt_2/Transformer/transformer_18_2024-04-13-19-42/best_model.pth'
  angle_3:
    resnet18: '/fashuxu/IMR-MCF/ckpt/angle_3/ResNet/resnet18_2024-05-10-13-56/best_model.pth'
    resnet34: '/fashuxu/IMR-MCF/ckpt/angle_3/ResNet/resnet34_2024-05-11-13-13/best_model.pth'
    resnet50: '/fashuxu/IMR-MCF/ckpt/angle_3/ResNet/resnet50_2024-05-13-09-21/best_model.pth'
    resnet101: '/fashuxu/IMR-MCF/ckpt/angle_3/ResNet/resnet101_2024-05-25-12-36/best_model.pth'
    resnet152: '/fashuxu/IMR-MCF/ckpt/angle_3/ResNet/resnet152_2024-05-28-02-39/best_model.pth'
    mlp: '/fashuxu/IMR-MCF-All/ckpt_3/MLP/mlp_2024-06-13-14-45/best_model.pth'
    lstm_5: '/fashuxu/IMR-MCF-All/ckpt_3/LSTM/5_2024-04-13-20-00/best_model.pth'
    lstm_10: '/fashuxu/IMR-MCF-All/ckpt_3/LSTM/10_2024-04-13-20-00/best_model.pth'
    lstm_15: '/fashuxu/IMR-MCF-All/ckpt_3/LSTM/15_2024-04-13-20-00/best_model.pth'
    lstm_20: '/fashuxu/IMR-MCF-All/ckpt_3/LSTM/20_2024-04-13-20-01/best_model.pth'
    transformer_6: '/fashuxu/IMR-MCF-All/ckpt_3/Transformer/transformer_6_2024-04-13-22-59/best_model.pth'
    transformer_12: '/fashuxu/IMR-MCF-All/ckpt_3/Transformer/transformer_12_2024-04-13-22-59/best_model.pth'
    transformer_18: '/fashuxu/IMR-MCF-All/ckpt_3/Transformer/transformer_18_2024-04-13-23-00/best_model.pth'